//AddWatchWindowVars Build 2
expRemoveAll()
//Variables
expAdd ("BuildInfo",getNatural())
expAdd ("boardStatus",getNatural())
expAdd ("clearTrip", getNatural())
expAdd ("iLRef",getNatural())
expAdd ("closeGiLoop",getNatural())
expAdd ("EPwm1Regs.TZFLG.all",getNatural())
expAdd ("EPwm2Regs.TZFLG.all",getNatural())
expAdd ("EPwm3Regs.TZFLG.all",getNatural())
expAdd ("guiVbus",getNatural())
expAdd ("guiVbusPM",getNatural())
expAdd ("guiVbusMN",getNatural())
expAdd ("guiVrms1",getNatural())
expAdd ("guiVrms2",getNatural())
expAdd ("guiVrms3",getNatural())
expAdd ("guiIrms1",getNatural())
expAdd ("guiIrms2",getNatural())
expAdd ("guiIrms3",getNatural())
expAdd ("guiPF1",getNatural())
expAdd ("guiPF2",getNatural())
expAdd ("guiPF3",getNatural())