$solution = {
    name                 : 'TIDM1000_TIDM1000_pfc3phvienna_F2837x',
    cpuSysClock          : 200,
    PWMSysClkFreq		 : 100,
    eCAPSysClkFreq		 : 200,
	adcMaxRange			 : 3.3,
    pwmSwitchingFreq     : {min : 20, max : 200, default : 100},
    vInSenseMaxDefault  : 13.3,
    vOutSenseMaxDefault : 9.76,
    iLMaxSensedDefault   : 5.5,
    iLTripLevelDefault   : 4.0,
	
    adcPinVOUTPM           : [{label : 'ADC_C2', pin : 2, module : 3},
                            {label : 'ADC_C3', pin : 3, module : 3},
                            {label : 'ADC_C4', pin : 4, module : 3},
                            {label : 'ADC_C5', pin : 5, module : 3},
                            {label : 'ADC_IN14', pin : 14, module : 3},
    						{label : 'ADC_IN15', pin : 15, module : 3}],
    adcPinVOUTMN           : [{label : 'ADC_C2', pin : 2, module : 3},
                            {label : 'ADC_C3', pin : 3, module : 3},
                            {label : 'ADC_C4', pin : 4, module : 3},
                            {label : 'ADC_C5', pin : 5, module : 3},
                            {label : 'ADC_IN14', pin : 14, module : 3},
    						{label : 'ADC_IN15', pin : 15, module : 3}],
    adcPinVIN1	          : [{label : 'ADC_B0', pin : 0, module : 2},
                            {label : 'ADC_B1', pin : 1, module : 2},
                            {label : 'ADC_B2', pin : 2, module : 2},
                            {label : 'ADC_B3', pin : 3, module : 2},
                            {label : 'ADC_B4', pin : 4, module : 2},
                            {label : 'ADC_B5', pin : 5, module : 2},
                            {label : 'ADC_IN14', pin : 14, module : 2},
    						{label : 'ADC_IN15', pin : 15, module : 2}],
    adcPinVIN2	          : [{label : 'ADC_D0', pin : 0, module : 4},
                            {label : 'ADC_D1', pin : 1, module : 4},
                            {label : 'ADC_D2', pin : 2, module : 4},
                            {label : 'ADC_D3', pin : 3, module : 4},
                            {label : 'ADC_D4', pin : 4, module : 4},
                            {label : 'ADC_D5', pin : 5, module : 4},
                            {label : 'ADC_IN14', pin : 14, module : 4},
     						{label : 'ADC_IN15', pin : 15, module : 4}],
	adcPinVIN3	          : [{label : 'ADC_D0', pin : 0, module : 4},
                            {label : 'ADC_D1', pin : 1, module : 4},
                            {label : 'ADC_D2', pin : 2, module : 4},
                            {label : 'ADC_D3', pin : 3, module : 4},
                            {label : 'ADC_D4', pin : 4, module : 4},
                            {label : 'ADC_D5', pin : 5, module : 4},
                            {label : 'ADC_IN14', pin : 14, module : 4},
     						{label : 'ADC_IN15', pin : 15, module : 4}],
    adcPinIL1         	: [{label : 'ADC_A2/COMP1+', pin : 2, module : 1, comparator : 1},
                           {label : 'ADC_A4/COMP2+',  pin : 4, module : 1, comparator : 2},
                           {label : 'ADC_IN14/COMP4+',  pin : 14, module : 1, comparator : 4}],
    adcPinIL2         	: [{label : 'ADC_A2/COMP1+', pin : 2, module : 1, comparator : 1},
                           {label : 'ADC_A4/COMP2+',  pin : 4, module : 1, comparator : 2},
                           {label : 'ADC_IN14/COMP4+',  pin : 14, module : 1, comparator : 4}],
    adcPinIL3         	: [{label : 'ADC_A2/COMP1+', pin : 2, module : 1, comparator : 1},
                           {label : 'ADC_A4/COMP2+',  pin : 4, module : 1, comparator : 2},
                           {label : 'ADC_IN14/COMP4+',  pin : 14, module : 1, comparator : 4}],
    
    INCR_BUILD      	 : [{label : '1: Open Loop', value : 1},
                    	    {label : '2: Closed Current Loop', value : 2},
                    	    {label : '3: Closed Voltage & Current Loop', value : 3},
                    	    {label : '4: Closed Voltage, Current & Bus Cap Balance Loop', value : 4}],
                    	    
    ControlISRCore   :[{label : 'C28x', value : 1},
                   	       {label : 'CLA', value : 2}],
                    	                	    
    Tuning			 	 : [{label : 'None', value : 0},
        				    {label : 'Current Loop / Gi', value : 1},
                          	{label : 'Voltage Loop / Gv', value : 2},
                         	{label : 'Balance Loop / Gs', value : 3}],  
                         	                             	    
    COMP_NUM             : [{label : '-', value : 0},
                            {label : '1', value : 1},
                            {label : '2', value : 2},
                            {label : '3', value : 3}],
                                                            		    
    Style	             : [{label : '-', value : 0},
         	                {label : 'PID', value : 1},
                            {label : '2P2Z', value : 2},
                            {label : 'Lead Lag', value : 8},
                            {label : 'P', value : 9}], 
                            
	Fsw_Fctrl_Ratio      : [{label : 'Current Loop ISR runs at Fsw', value : 1},
                            {label : 'Current Loop ISR runs at Fsw/2', value : 2},
                            {label : 'Current Loop ISR runs at Fsw/3', value : 3}],
   
    Voltage_Loop_Ratio	 : [{label : 'Voltage Loop runs at Current ISR', value: 1}],
	   
    SensingOption		 : [{label : 'ADC', value : 1},
                 		    {label : 'SDFM', value : 2}],
                      	       
    pwmNo				 : [{label : 'PWM1, PWM2, PWM3'}],
                            
};
